// Redis command list for CLI autocomplete
export const REDIS_COMMANDS: Record<string, { args: string; summary: string }> = {
  APPEND: { args: 'key value', summary: 'Append a value to a key' },
  AUTH: { args: '[username] password', summary: 'Authenticate to the server' },
  BGSAVE: { args: '', summary: 'Asynchronously save the dataset to disk' },
  BGREWRITEAOF: { args: '', summary: 'Asynchronously rewrite the append-only file' },
  BITCOUNT: { args: 'key [start end]', summary: 'Count set bits in a string' },
  BITOP: { args: 'operation destkey key [key ...]', summary: 'Perform bitwise operations between strings' },
  BITPOS: { args: 'key bit [start] [end]', summary: 'Find first bit set or clear in a string' },
  BLPOP: { args: 'key [key ...] timeout', summary: 'Remove and get the first element in a list, or block until one is available' },
  BRPOP: { args: 'key [key ...] timeout', summary: 'Remove and get the last element in a list, or block until one is available' },
  BRPOPLPUSH: { args: 'source destination timeout', summary: 'Pop a value from a list, push it to another list and return it; or block until one is available' },
  CLIENT: { args: 'subcommand [argument [argument ...]]', summary: 'Get the list of client connections' },
  CLUSTER: { args: 'subcommand [argument [argument ...]]', summary: 'Run a Cluster command' },
  COMMAND: { args: '', summary: 'Get array of Redis command details' },
  CONFIG: { args: 'subcommand argument', summary: 'Get, set, or reset Redis configuration parameters' },
  COPY: { args: 'source destination [DB destination-db] [REPLACE]', summary: 'Copy a key' },
  DBSIZE: { args: '', summary: 'Return the number of keys in the selected database' },
  DEBUG: { args: 'subcommand [argument [argument ...]]', summary: 'A container for debugging commands' },
  DECR: { args: 'key', summary: 'Decrement the integer value of a key by one' },
  DECRBY: { args: 'key decrement', summary: 'Decrement the integer value of a key by the given number' },
  DEL: { args: 'key [key ...]', summary: 'Delete a key' },
  DISCARD: { args: '', summary: 'Discard all commands issued after MULTI' },
  DUMP: { args: 'key', summary: 'Return a serialized version of the value stored at the specified key' },
  ECHO: { args: 'message', summary: 'Echo the given string' },
  EVAL: { args: 'script numkeys [key [key ...]] [arg [arg ...]]', summary: 'Execute a Lua script server side' },
  EVALSHA: { args: 'sha1 numkeys [key [key ...]] [arg [arg ...]]', summary: 'Execute a Lua script server side' },
  EXEC: { args: '', summary: 'Execute all commands issued after MULTI' },
  EXISTS: { args: 'key [key ...]', summary: 'Determine if a key exists' },
  EXPIRE: { args: 'key seconds', summary: 'Set a key\'s time to live in seconds' },
  EXPIREAT: { args: 'key timestamp', summary: 'Set the expiration for a key as a UNIX timestamp' },
  EXPIRETIME: { args: 'key', summary: 'Get the expiration Unix timestamp for a key' },
  FLUSHALL: { args: '[ASYNC | SYNC]', summary: 'Remove all keys from all databases' },
  FLUSHDB: { args: '[ASYNC | SYNC]', summary: 'Remove all keys from the current database' },
  GEOADD: { args: 'key [NX | XX] [GET] longitude latitude member [longitude latitude member ...]', summary: 'Add one or more geospatial items in the geospatial index represented using a sorted set' },
  GEODIST: { args: 'key member1 member2 [M | KM | FT | MI]', summary: 'Returns the distance between two members in the geospatial index represented by the sorted set' },
  GEOPOS: { args: 'key member [member ...]', summary: 'Returns longitude and latitude of members of a geospatial index' },
  GEORADIUS: { args: 'key longitude latitude radius M | KM | FT | MI', summary: 'Query a sorted set representing a geospatial index to fetch members matching a given maximum distance from a point' },
  GEOSEARCH: { args: 'key FROMMEMBER member | FROMLONLAT longitude latitude BYRADIUS radius M | KM | FT | MI | BYBOX width height M | KM | FT | MI ASC | DESC', summary: 'Query a sorted set representing a geospatial index to fetch members inside an area of a box or a circle' },
  GET: { args: 'key', summary: 'Get the value of a key' },
  GETBIT: { args: 'key offset', summary: 'Returns the bit value at offset in the string value stored at key' },
  GETDEL: { args: 'key', summary: 'Get the value of a key and delete the key' },
  GETEX: { args: 'key [EX seconds | PX milliseconds | EXAT unix-time-seconds | PXAT unix-time-milliseconds | PERSIST]', summary: 'Get the value of a key and optionally set its expiration' },
  GETRANGE: { args: 'key start end', summary: 'Get a substring of the string stored at a key' },
  GETSET: { args: 'key value', summary: 'Set the string value of a key and return its old value' },
  HDEL: { args: 'key field [field ...]', summary: 'Delete one or more hash fields' },
  HEXISTS: { args: 'key field', summary: 'Determine if a hash field exists' },
  HGET: { args: 'key field', summary: 'Get the value of a hash field' },
  HGETALL: { args: 'key', summary: 'Get all the fields and values in a hash' },
  HINCRBY: { args: 'key field increment', summary: 'Increment the integer value of a hash field by the given number' },
  HINCRBYFLOAT: { args: 'key field increment', summary: 'Increment the float value of a hash field by the given amount' },
  HKEYS: { args: 'key', summary: 'Get all the fields in a hash' },
  HLEN: { args: 'key', summary: 'Get the number of fields in a hash' },
  HMGET: { args: 'key field [field ...]', summary: 'Get the values of all the given hash fields' },
  HMSET: { args: 'key field value [field value ...]', summary: 'Set multiple hash fields to multiple values' },
  HSCAN: { args: 'key cursor [MATCH pattern] [COUNT count]', summary: 'Incrementally iterate hash fields and associated values' },
  HSET: { args: 'key field value [field value ...]', summary: 'Set the string value of a hash field' },
  HSETNX: { args: 'key field value', summary: 'Set the value of a hash field, only if the field does not exist' },
  HVALS: { args: 'key', summary: 'Get all the values in a hash' },
  INCR: { args: 'key', summary: 'Increment the integer value of a key by one' },
  INCRBY: { args: 'key increment', summary: 'Increment the integer value of a key by the given amount' },
  INCRBYFLOAT: { args: 'key increment', summary: 'Increment the float value of a key by the given amount' },
  INFO: { args: '[section [section ...]]', summary: 'Get information and statistics about the server' },
  KEYS: { args: 'pattern', summary: 'Find all keys matching the given pattern' },
  LASTSAVE: { args: '', summary: 'Get the UNIX time stamp of the last successful save to disk' },
  LINDEX: { args: 'key index', summary: 'Get an element from a list by its index' },
  LINSERT: { args: 'key BEFORE | AFTER pivot element', summary: 'Insert an element before or after another element in a list' },
  LLEN: { args: 'key', summary: 'Get the length of a list' },
  LMOVE: { args: 'source destination LEFT | RIGHT LEFT | RIGHT', summary: 'Pop an element from one list, push to another list and return it' },
  LPOP: { args: 'key [count]', summary: 'Remove and get the first elements in a list' },
  LPOS: { args: 'key element [RANK rank] [COUNT num-matches] [MAXLEN len]', summary: 'Return the index of matching elements on a list' },
  LPUSH: { args: 'key element [element ...]', summary: 'Prepend one or multiple elements to a list' },
  LPUSHX: { args: 'key element [element ...]', summary: 'Prepend an element to a list, only if the list exists' },
  LRANGE: { args: 'key start stop', summary: 'Get a range of elements from a list' },
  LREM: { args: 'key count element', summary: 'Remove elements from a list' },
  LSET: { args: 'key index element', summary: 'Set the value of an element in a list by its index' },
  LTRIM: { args: 'key start stop', summary: 'Trim a list to the specified range' },
  MEMORY: { args: 'subcommand [argument [argument ...]]', summary: 'A container for memory introspection commands' },
  MGET: { args: 'key [key ...]', summary: 'Get the values of all the given keys' },
  MIGRATE: { args: 'host port key | "" destination-db timeout [COPY] [REPLACE] [AUTH password | AUTH2 username password] [KEYS key [key ...]]', summary: 'Atomically transfer a key from a Redis instance to another one' },
  MONITOR: { args: '', summary: 'Listen for all requests received by the server in real time' },
  MOVE: { args: 'key db', summary: 'Move a key to another database' },
  MSET: { args: 'key value [key value ...]', summary: 'Set multiple keys to multiple values' },
  MSETNX: { args: 'key value [key value ...]', summary: 'Set multiple keys to multiple values, only if none of the keys exist' },
  MULTI: { args: '', summary: 'Mark the start of a transaction block' },
  OBJECT: { args: 'subcommand [arguments [arguments ...]]', summary: 'A container for object introspection commands' },
  PERSIST: { args: 'key', summary: 'Remove the expiration from a key' },
  PEXPIRE: { args: 'key milliseconds', summary: 'Set a key\'s time to live in milliseconds' },
  PEXPIREAT: { args: 'key milliseconds-timestamp', summary: 'Set the expiration for a key as a UNIX timestamp specified in milliseconds' },
  PING: { args: '[message]', summary: 'Ping the server' },
  PSETEX: { args: 'key milliseconds value', summary: 'Set the value and expiration in milliseconds of a key' },
  PSUBSCRIBE: { args: 'pattern [pattern ...]', summary: 'Listen for messages published to channels matching the given patterns' },
  PTTL: { args: 'key', summary: 'Get the time to live for a key in milliseconds' },
  PUBLISH: { args: 'channel message', summary: 'Post a message to a channel' },
  PUBSUB: { args: 'subcommand [argument [argument ...]]', summary: 'A container for Pub/Sub commands' },
  PUNSUBSCRIBE: { args: '[pattern [pattern ...]]', summary: 'Stop listening for messages posted to channels matching the given patterns' },
  QUIT: { args: '', summary: 'Close the connection' },
  RANDOMKEY: { args: '', summary: 'Return a random key from the keyspace' },
  RENAME: { args: 'key newkey', summary: 'Rename a key' },
  RENAMENX: { args: 'key newkey', summary: 'Rename a key, only if the new key does not exist' },
  RESET: { args: '', summary: 'Reset the connection' },
  RESTORE: { args: 'key ttl serialized-value [REPLACE] [ABSTTL] [IDLETIME seconds] [FREQ frequency]', summary: 'Create a key using the provided serialized value, previously obtained using DUMP' },
  RPOP: { args: 'key [count]', summary: 'Remove and get the last elements in a list' },
  RPOPLPUSH: { args: 'source destination', summary: 'Remove the last element in a list, prepend it to another list and return it' },
  RPUSH: { args: 'key element [element ...]', summary: 'Append one or multiple elements to a list' },
  RPUSHX: { args: 'key element [element ...]', summary: 'Append an element to a list, only if the list exists' },
  SADD: { args: 'key member [member ...]', summary: 'Add one or more members to a set' },
  SAVE: { args: '', summary: 'Synchronously save the dataset to disk' },
  SCAN: { args: 'cursor [MATCH pattern] [COUNT count] [TYPE type]', summary: 'Incrementally iterate the keys space' },
  SCARD: { args: 'key', summary: 'Get the number of members in a set' },
  SDIFF: { args: 'key [key ...]', summary: 'Subtract multiple sets' },
  SELECT: { args: 'index', summary: 'Change the selected database for the current connection' },
  SET: { args: 'key value [NX | XX] [GET] [EX seconds | PX milliseconds | EXAT unix-time-seconds | PXAT unix-time-milliseconds | KEEPTTL]', summary: 'Set the string value of a key' },
  SETBIT: { args: 'key offset value', summary: 'Sets or clears the bit at offset in the string value stored at key' },
  SETEX: { args: 'key seconds value', summary: 'Set the value and expiration of a key' },
  SETNX: { args: 'key value', summary: 'Set the value of a key, only if the key does not exist' },
  SETRANGE: { args: 'key offset value', summary: 'Overwrite part of a string at key starting at the specified offset' },
  SHUTDOWN: { args: '[NOSAVE | SAVE] [NOW] [FORCE] [ABORT]', summary: 'Synchronously save the dataset to disk and then shut down the server' },
  SINTERSTORE: { args: 'destination key [key ...]', summary: 'Intersect multiple sets and store the resulting set in a key' },
  SLOWLOG: { args: 'subcommand [argument]', summary: 'A container for slow log commands' },
  SMEMBERS: { args: 'key', summary: 'Get all the members in a set' },
  SMISMEMBER: { args: 'key member [member ...]', summary: 'Returns the membership associated with the given elements for a set' },
  SMOVE: { args: 'source destination member', summary: 'Move a member from one set to another' },
  SORT: { args: 'key [BY pattern] [LIMIT offset count] [GET pattern [GET pattern ...]] [ASC | DESC] [ALPHA] [STORE destination]', summary: 'Sort the elements in a list, set or sorted set' },
  SPOP: { args: 'key [count]', summary: 'Remove and return one or multiple random members from a set' },
  SRANDMEMBER: { args: 'key [count]', summary: 'Get one or multiple random members from a set' },
  SREM: { args: 'key member [member ...]', summary: 'Remove one or more members from a set' },
  SSCAN: { args: 'key cursor [MATCH pattern] [COUNT count]', summary: 'Incrementally iterate Set elements' },
  STRLEN: { args: 'key', summary: 'Get the length of the value stored in a key' },
  SUBSCRIBE: { args: 'channel [channel ...]', summary: 'Listen for messages published to the given channels' },
  SUBSTR: { args: 'key start end', summary: 'Get a substring of the string stored at a key' },
  SUNION: { args: 'key [key ...]', summary: 'Add multiple sets' },
  SUNIONSTORE: { args: 'destination key [key ...]', summary: 'Add multiple sets and store the resulting set in a key' },
  TIME: { args: '', summary: 'Return the current server time' },
  TTL: { args: 'key', summary: 'Get the time to live for a key in seconds' },
  TYPE: { args: 'key', summary: 'Determine the type stored at key' },
  UNSUBSCRIBE: { args: '[channel [channel ...]]', summary: 'Stop listening for messages posted to the given channels' },
  UNWATCH: { args: '', summary: 'Forget about all watched keys' },
  WAIT: { args: 'numreplicas timeout', summary: 'Wait for the synchronous replication of all the write commands sent in the context of the current connection' },
  WATCH: { args: 'key [key ...]', summary: 'Watch the given keys to determine execution of the MULTI/EXEC block' },
  XADD: { args: 'key [NOMKSTREAM] [MAXLEN | MINID [= | ~] threshold [LIMIT count]] * | id field value [field value ...]', summary: 'Appends a new entry to a stream' },
  XDEL: { args: 'key id [id ...]', summary: 'Removes the specified entries from the stream' },
  XLEN: { args: 'key', summary: 'Return the number of entries in a stream' },
  XRANGE: { args: 'key start end [COUNT count]', summary: 'Return a range of elements in a stream, with IDs matching the specified IDs interval' },
  XREAD: { args: 'COUNT count BLOCK milliseconds STREAMS key [key ...] id [id ...]', summary: 'Return never seen elements in multiple streams, with IDs greater than the ones reported by the caller for each stream' },
  XREVRANGE: { args: 'key end start [COUNT count]', summary: 'Return a range of elements in a stream, with IDs matching the specified IDs interval, in reverse order' },
  XTRIM: { args: 'key MAXLEN | MINID [= | ~] threshold [LIMIT count]', summary: 'Trims the stream to a given number of items' },
  ZADD: { args: 'key [NX | XX] [GT | LT] [CH] [INCR] score member [score member ...]', summary: 'Add one or more members to a sorted set, or update its score if it already exists' },
  ZCARD: { args: 'key', summary: 'Get the number of members in a sorted set' },
  ZCOUNT: { args: 'key min max', summary: 'Count the members in a sorted set with scores within the given values' },
  ZDIFF: { args: 'numkeys key [key ...] [WITHSCORES]', summary: 'Subtract multiple sorted sets' },
  ZINCRBY: { args: 'key increment member', summary: 'Increment the score of a member in a sorted set' },
  ZINTER: { args: 'numkeys key [key ...] [WEIGHTS weight [weight ...]] [AGGREGATE SUM | MIN | MAX] [WITHSCORES]', summary: 'Intersect multiple sorted sets' },
  ZINTERSTORE: { args: 'destination numkeys key [key ...] [WEIGHTS weight [weight ...]] [AGGREGATE SUM | MIN | MAX]', summary: 'Intersect multiple sorted sets and store the resulting sorted set in a new key' },
  ZLEXCOUNT: { args: 'key min max', summary: 'Count the number of members in a sorted set between a given lexicographical range' },
  ZMSCORE: { args: 'key member [member ...]', summary: 'Get the score associated with the given members in a sorted set' },
  ZPOPMAX: { args: 'key [count]', summary: 'Remove and return members with the highest scores in a sorted set' },
  ZPOPMIN: { args: 'key [count]', summary: 'Remove and return members with the lowest scores in a sorted set' },
  ZRANDMEMBER: { args: 'key [count [WITHSCORES]]', summary: 'Get one or multiple random elements from a sorted set' },
  ZRANGE: { args: 'key min max [BYSCORE | BYLEX] [REV] [LIMIT offset count] [WITHSCORES]', summary: 'Return a range of members in a sorted set' },
  ZRANGEBYLEX: { args: 'key min max [LIMIT offset count]', summary: 'Return a range of members in a sorted set, by lexicographical range' },
  ZRANGEBYSCORE: { args: 'key min max [WITHSCORES] [LIMIT offset count]', summary: 'Return a range of members in a sorted set, by score' },
  ZRANGESTORE: { args: 'dst src min max [BYSCORE | BYLEX] [REV] [LIMIT offset count]', summary: 'Store a range of members from sorted set into another key' },
  ZRANK: { args: 'key member [WITHSCORE]', summary: 'Determine the index of a member in a sorted set' },
  ZREM: { args: 'key member [member ...]', summary: 'Remove one or more members from a sorted set' },
  ZREMRANGEBYLEX: { args: 'key min max', summary: 'Remove all members in a sorted set between the given lexicographical range' },
  ZREMRANGEBYRANK: { args: 'key start stop', summary: 'Remove all members in a sorted set within the given indexes' },
  ZREMRANGEBYSCORE: { args: 'key min max', summary: 'Remove all members in a sorted set within the given scores' },
  ZREVRANGE: { args: 'key start stop [WITHSCORES]', summary: 'Return a range of members in a sorted set, by index, with scores ordered from high to low' },
  ZREVRANGEBYLEX: { args: 'key max min [LIMIT offset count]', summary: 'Return a range of members in a sorted set, by lexicographical range, ordered from higher to lower strings' },
  ZREVRANGEBYSCORE: { args: 'key max min [WITHSCORES] [LIMIT offset count]', summary: 'Return a range of members in a sorted set, by score, with scores ordered from high to low' },
  ZREVRANK: { args: 'key member [WITHSCORE]', summary: 'Determine the index of a member in a sorted set, with scores ordered from high to low' },
  ZSCAN: { args: 'key cursor [MATCH pattern] [COUNT count]', summary: 'Incrementally iterate sorted sets elements and associated scores' },
  ZSCORE: { args: 'key member', summary: 'Get the score associated with the given member in a sorted set' },
  ZUNION: { args: 'numkeys key [key ...] [WEIGHTS weight [weight ...]] [AGGREGATE SUM | MIN | MAX] [WITHSCORES]', summary: 'Add multiple sorted sets' },
  ZUNIONSTORE: { args: 'destination numkeys key [key ...] [WEIGHTS weight [weight ...]] [AGGREGATE SUM | MIN | MAX]', summary: 'Add multiple sorted sets and store the resulting sorted set in a new key' },
}

export const COMMAND_NAMES = Object.keys(REDIS_COMMANDS)
